# Experiment paths
paths:
  train_file: dataset/train_data.csv
  val_file: dataset/val_data.csv
  target_col: LACa
  mlp_config: configs/models/MLP.yaml
  tabm_config: configs/models/tabM.yaml
  encoder_config: configs/models/encoder.yaml
  vae_encoder_config: configs/models/vae_encoder.yaml
