# Training arguments defaults
seed: 42
split_size: 0.2
exclude_cols: [LVEF_dis,LACm]

loader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2
  persistent_workers: true

training:
  learning_rate: 0.001
  epochs: 50
  batch_size: 64
  weight_decay: 1e-5
  apply_normalization: true

